name: Terraform 

on: [push]

# Uncomment below when you have the environment variables set up
env: 
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }} 

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: 1.1.9
        
    - name: Terraform Init 
      working-directory: ./terraform/
      run: terraform init 
      
    - name: Validate 
      run: terraform validate 
      
    - name: Format 
      run: terraform fmt -check 
      
    - name: Plan T
      working-directory: ./terraform/
      run: terraform plan
